# ANN - Artificial Neural Networks using TensorFlow Framework.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
pip install tensorflow

In [3]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [5]:
df = pd.read_csv("Churn_Modelling.csv")

In [6]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [8]:
df.shape

(10000, 14)

In [9]:
df.size

140000

In [10]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [12]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [13]:
df["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [14]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [15]:
import tensorflow as tf

In [16]:
import warnings
warnings.filterwarnings("ignore")

In [18]:
tf.__version__

'2.15.0'

# Part 1 Data Preprocessing

In [22]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [30]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [29]:
print(y)

[1 0 1 ... 1 1 0]


In [31]:
X[:,2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

# Encoding Categorical data.

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [33]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
# one hot encoding geography column.

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [ ('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [37]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Split the data into train test

In [40]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train ,y_test = train_test_split(X,y,test_size =0.2 ,random_state = 0)

# Feature scaling

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [43]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [44]:
X_test

array([[-0.95692675,  1.62776996, -0.57427105, ...,  0.66011376,
         0.97628121,  1.62185911],
       [ 1.04501206, -0.61433742, -0.57427105, ...,  0.66011376,
        -1.02429504,  0.504204  ],
       [-0.95692675, -0.61433742,  1.74133801, ...,  0.66011376,
         0.97628121, -0.41865644],
       ...,
       [-0.95692675, -0.61433742,  1.74133801, ...,  0.66011376,
        -1.02429504,  0.72775202],
       [-0.95692675,  1.62776996, -0.57427105, ...,  0.66011376,
         0.97628121, -1.54162886],
       [-0.95692675,  1.62776996, -0.57427105, ...,  0.66011376,
        -1.02429504,  1.62356528]])

# Part 2 - Building ANN model.

# Intializing the ANN 

In [45]:
ann = tf.keras.models.Sequential()

# Adding the input layer and first hidden layer.

In [46]:
ann.add(tf.keras.layers.Dense(units = 6 , activation='relu'))

# Adding the second hidden layer.

In [47]:
ann.add(tf.keras.layers.Dense(units=6 , activation = 'relu'))

# As many hidden layers you can add that much micromanagement will take place.And will take more time.

# Adding the output layer.

In [48]:
ann.add(tf.keras.layers.Dense(units=1 , activation = 'sigmoid'))

# Part 3 - Training the ANN

# Compiling the ANN

In [49]:
ann.compile(optimizer = 'adam' ,loss = 'binary_crossentropy',metrics = ['accuracy'])

# Training the ANN on the train set

In [50]:
# epoch and batch size are hyperparameter for deep learning.
ann.fit(X_train , y_train , batch_size=32, epochs=5)

Epoch 1/5


250/250 [==============================] - 2s 3ms/step - loss: 0.6881 - accuracy: 0.6106
Epoch 2/5
250/250 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7961
Epoch 3/5
250/250 [==============================] - 1s 2ms/step - loss: 0.4488 - accuracy: 0.7989
Epoch 4/5
250/250 [==============================] - 1s 2ms/step - loss: 0.4283 - accuracy: 0.8019
Epoch 5/5
250/250 [==============================] - 1s 3ms/step - loss: 0.4123 - accuracy: 0.8033


# Part 4 - Making the predictions and evaluating the model.

# Predicting the result of a single observation.

In [ ]:
# Use our ANN model to predict the customer with the followinginformations will leave the bank or not
"""Geography = France
Credit_score = 600
Gender = Male
Age = 40 years old
Tenure = 3years
balance = $60000
Number of products = 2
Does this customer has credit card = yes
Estimated salary = $50000
Is the customer an active member = yes
so should we say goodbye to customer ? """

# solution

In [53]:
normalized_data = sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])

In [54]:
print(ann.predict(normalized_data > 0.5))

1/1 [==============================] - 0s 86ms/step
[[0.04515466]]


# This customer remains in the bank as output is less then 0.5 which is equal to 0 so the customer does not leave.
# If it was greater then 0.5 then customer would have left the bank.

# Predicting the test results.

In [55]:
y_pred = ann.predict(X_test)

63/63 [==============================] - 0s 2ms/step


In [61]:
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [62]:
from sklearn.metrics import accuracy_score

accuracies = accuracy_score(y_test,y_pred)
accuracies

0.8055

# Making the confusion matrix.

In [63]:
from sklearn.metrics import confusion_matrix

In [64]:
cm = confusion_matrix(y_test,y_pred)

In [65]:
cm

array([[1567,   28],
       [ 361,   44]], dtype=int64)

In [70]:
print(cm)

[[1567   28]
 [ 361   44]]
